/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGCFFI


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif




#ifdef __cplusplus
#  define EXTERN   extern "C"
#else
#  define EXTERN   extern
#endif

#define EXPORT   EXTERN SWIGEXPORT

#include <string.h>



#ifdef __cplusplus
#  define EXTERN   extern "C"
#else
#  define EXTERN   extern
#endif

#define EXPORT   EXTERN SWIGEXPORT

#include <string.h>
#include <stdlib.h>

                                                                                             
/* Includes the header in the wrapper code */                                                  
/* #include "Rinterface.h"         */
#include "/usr/include/R/Rinterface.h"                                                                                                                                                

EXPORT void _wrap_R_RestoreGlobalEnv () {
  try {
    R_RestoreGlobalEnv();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_R_RestoreGlobalEnvFromFile (char *larg1, Rboolean *larg2) {
  char *arg1 = (char *) 0 ;
  Rboolean arg2 ;
  
  arg1 = larg1;
  arg2 = *larg2;
  try {
    R_RestoreGlobalEnvFromFile((char const *)arg1,arg2);
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_R_SaveGlobalEnv () {
  try {
    R_SaveGlobalEnv();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_R_SaveGlobalEnvToFile (char *larg1) {
  char *arg1 = (char *) 0 ;
  
  arg1 = larg1;
  try {
    R_SaveGlobalEnvToFile((char const *)arg1);
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_R_FlushConsole () {
  try {
    R_FlushConsole();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_R_ClearerrConsole () {
  try {
    R_ClearerrConsole();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_R_Suicide (char *larg1) {
  char *arg1 = (char *) 0 ;
  
  arg1 = larg1;
  try {
    R_Suicide((char const *)arg1);
    
  } catch (...) {
    
  }
}


EXPORT char *_wrap_R_HomeDir () {
  char * lresult = (char *)0 ;
  char *result = 0 ;
  
  try {
    result = (char *)R_HomeDir();
    lresult = result;
    return lresult;
  } catch (...) {
    return (char *)0;
  }
}


EXPORT void _wrap_R_setupHistory () {
  try {
    R_setupHistory();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_Rf_jump_to_toplevel () {
  try {
    Rf_jump_to_toplevel();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_Rf_mainloop () {
  try {
    Rf_mainloop();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_Rf_onintr () {
  try {
    Rf_onintr();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_process_site_Renviron () {
  try {
    process_site_Renviron();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_process_system_Renviron () {
  try {
    process_system_Renviron();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_process_user_Renviron () {
  try {
    process_user_Renviron();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_R_setStartTime () {
  try {
    R_setStartTime();
    
  } catch (...) {
    
  }
}


EXPORT void _wrap_fpu_setup (Rboolean *larg1) {
  Rboolean arg1 ;
  
  arg1 = *larg1;
  try {
    fpu_setup(arg1);
    
  } catch (...) {
    
  }
}


