;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.2
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (cl:&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cffi:defcvar ("R_Interactive" R_Interactive)
 :pointer)

(cffi:defcvar ("R_Slave" R_Slave)
 :pointer)

(cffi:defcfun ("_wrap_R_RestoreGlobalEnv" R_RestoreGlobalEnv) :void)

(cffi:defcfun ("_wrap_R_RestoreGlobalEnvFromFile" R_RestoreGlobalEnvFromFile) :void
  (arg0 :string)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_R_SaveGlobalEnv" R_SaveGlobalEnv) :void)

(cffi:defcfun ("_wrap_R_SaveGlobalEnvToFile" R_SaveGlobalEnvToFile) :void
  (arg0 :string))

(cffi:defcfun ("_wrap_R_FlushConsole" R_FlushConsole) :void)

(cffi:defcfun ("_wrap_R_ClearerrConsole" R_ClearerrConsole) :void)

(cffi:defcfun ("_wrap_R_Suicide" R_Suicide) :void
  (arg0 :string))

(cffi:defcfun ("_wrap_R_HomeDir" R_HomeDir) :string)

(cffi:defcvar ("R_DirtyImage" R_DirtyImage)
 :int)

(cffi:defcvar ("R_GUIType" R_GUIType)
 :string)

(cffi:defcfun ("_wrap_R_setupHistory" R_setupHistory) :void)

(cffi:defcvar ("R_HistoryFile" R_HistoryFile)
 :string)

(cffi:defcvar ("R_HistorySize" R_HistorySize)
 :int)

(cffi:defcvar ("R_RestoreHistory" R_RestoreHistory)
 :int)

(cffi:defcvar ("R_Home" R_Home)
 :string)

(cffi:defcfun ("_wrap_Rf_jump_to_toplevel" Rf_jump_to_toplevel) :void)

(cffi:defcfun ("_wrap_Rf_mainloop" Rf_mainloop) :void)

(cffi:defcfun ("_wrap_Rf_onintr" Rf_onintr) :void)

(cffi:defcvar ("R_GlobalContext" R_GlobalContext)
 :pointer)

(cffi:defcfun ("_wrap_process_site_Renviron" process_site_Renviron) :void)

(cffi:defcfun ("_wrap_process_system_Renviron" process_system_Renviron) :void)

(cffi:defcfun ("_wrap_process_user_Renviron" process_user_Renviron) :void)

(cffi:defcvar ("R_Consolefile" R_Consolefile)
 :pointer)

(cffi:defcvar ("R_Outputfile" R_Outputfile)
 :pointer)

(cffi:defcfun ("_wrap_R_setStartTime" R_setStartTime) :void)

(cffi:defcfun ("_wrap_fpu_setup" fpu_setup) :void
  (arg0 :pointer))

(cffi:defcvar ("R_SignalHandlers" R_SignalHandlers)
 :int)


